### ISSUE TITLE
Atom vim-surround uses different keybindings than classic vim-surround!

### ISSUE THREAD

**Issue by ypresto** [gepoch/vim-surround#12]
Surrounding selected text with `S` key is useful feature of original surround.vim!

**Comment by gepoch** [comment]
Hey! Not sure what you mean exactly...? Is visual highlight + `s "` not surrounding text for you?

Is there a command using uppercase `S` that I'm not aware of?

**Comment by ypresto** [comment]
Oh, sorry I'm not aware of `s` keymap...
Original vim-surround's mapping for visual mode is `S`, not `s`.

https://github.com/tpope/vim-surround/blob/master/plugin/surround.vim#L586

```
  xmap S   <Plug>VSurround
```

But I think it is good idea to use `s` mapping which has less key stroke than `S`!

**Comment by ypresto** [comment]
Oh, sorry I'm not aware of `s` keymap...
Original vim-surround's mapping for visual mode is `S`, not `s`.

https://github.com/tpope/vim-surround/blob/master/plugin/surround.vim#L586

```
  xmap S   <Plug>VSurround
```

But it's a great idea to use `s` mapping which has less key stroke than `S`!

**Comment by gepoch** [comment]
That's true!

The surround package probably does this to avoid shadowing the "substitute" command. However Atom can resolve ambiguous keybindings, so it takes a shortcut.

But this way of doing things certainly breaks backwards compatibility with peoples' muscle memory, which really isn't great...

Maybe we can make the dynamic keybindings configurable? Or include a tickbox for 'Legacy mode'

I definitely see the issue now :) I'll leave this ticket open as a place for discussion.

**Comment by ypresto** [comment]
I think it'll better to make it configurable if adding preferences.
Something like this:

```
== Key Binding ==
● S
○ s
○ Other key: [____]
```

**Comment by gepoch** [comment]
Configurability added in 0.5.0!

**Comment by ypresto** [comment]
thanks!!!!!
