### ISSUE TITLE
Adding custom wrapping characters causes extra wrappings to be put in the editor before refresh

### ISSUE THREAD

**Issue by murphyrandle** [gepoch/vim-surround#13]
Hi there! Thanks for making this package!

When I add custom characters to the plugin settings, and then try to use the plugin, I get a bunch of extra wrappings inserted into my editor. After refreshing the editor, the extra wrappings go away.

I'm guessing that probably the keybinding to trigger a wrapping is getting re-bound every time that settings box is edited, instead of the binding getting replaced.

That's all!

![screenshot 2015-03-12 15 39 42](https://cloud.githubusercontent.com/assets/1227109/6628864/9d22e582-c8ce-11e4-839e-343d1c2884a4.png)

**Comment by gepoch** [comment]
Ah! Yeah. Honestly my dynamic reconfiguring chops are probably pretty sloppy, and it's simple enough to referesh.

I'm onboard with fixing it though, as it's a UX speedbump.

**Comment by gepoch** [comment]
Fixed in 0.4.3!
