### ISSUE TITLE
Change Surround Command

### ISSUE THREAD

**Issue by gepoch** [gepoch/vim-surround#2]
`c s " '` (change double quotes to single quotes) and related commands are not implemented yet.

**Comment by geoffharcourt** [comment]
In order to implement this behavior, I think it would be useful to hook in to [vim-mode](atom/vim-mode)'s [text object functionality](https://github.com/atom/vim-mode/blob/master/lib/text-objects.coffee) rather than trying to implement it separately.

**Comment by gepoch** [comment]
I'll definitely file this away in the brain for later! :)

**Comment by geoffharcourt** [comment]
I'm taking a look at it myself, but I just wanted to avoid building two implementations of this behavior.

**Comment by lazutkin** [comment]
:+1:

**Comment by shemerey** [comment]
@gepoch, @geoffharcourt @lazutkin here is my attempt to do so https://github.com/gepoch/vim-surround/pull/20
