### ISSUE TITLE
Mutli cursor support seems to be broken

### ISSUE THREAD

**Issue by sgtpepper43** [gepoch/vim-surround#38]
![vim surround multi cursor atom](https://cloud.githubusercontent.com/assets/2449014/15023292/2214ce82-11ed-11e6-969e-b9f987259147.gif)

`cs'"`

It just copies the thing at the first cursor and puts it (along with the change) in the last cursor.
It must have broken since #8

**Comment by sgtpepper43** [comment]
Closing this because I don't want to see this issue in my issues list anymore and it [looks like the project is deprecated](https://github.com/gepoch/vim-surround#note-vim-surround-for-atom-is-obsoleted-by-vim-mode-plus-see-40-for-more-information)

**Comment by gepoch** [comment]
Hey @sgtpepper43 yep. Surround is now built into vim-mode-plus for atom, so you can configure everything you need in that package!

Thanks
