### ISSUE TITLE
Does not working with vim-mode-plus

### ISSUE THREAD

**Issue by notiv-nt** [gepoch/vim-surround#39]
Atom **1.10.0**
vim-mode-plus **0.56.0**

Does not working at all =(

**Comment by gepoch** [comment]
vim-mode-plus has builtin vim-surround features! You shouldn't need to use vim-surround with vim-mode-plus!

See https://github.com/t9md/atom-vim-mode-plus/wiki/Commands (search for "surround")

You should just need to set up some key bindings!

**Comment by notiv-nt** [comment]
I dont sure, but 

vim-mode-plus surround:
i must press `shift+s` and then `shift+9` for surround

but at vim-surround i press only `shift+9`

and it is not very convenient ((
