### ISSUE TITLE
Support vim-mode-plus

### ISSUE THREAD

**Issue by chadoh** [gepoch/vim-surround#40]
Great little plugin! Works great with `vim-mode`. But `vim-mode-plus` does so many things better than `vim-mode`, so I want to use it! But I can't because I'm so reliant on `vim-surround`, and `vim-surround` doesn't currently work with `vim-mode-plus`.

Note: this issue is the root cause of #35, noted in [this comment](https://github.com/gepoch/vim-surround/issues/35#issuecomment-213459944).

**Comment by gepoch** [comment]
vim-mode-plus implements its own surround commands, so vim-surround isn't necessary! There's a bit of up-front configuration, but it works great. See here for an example keymap setup: https://github.com/t9md/dotfiles/blob/master/atom/keymap.cson#L208

edit: And if it wasn't clear, this means you should uninstall vim-surround :)

**Comment by chadoh** [comment]
Great, thanks!

**Comment by kingluddite** [comment]
[This helped me figure it out](https://github.com/t9md/atom-vim-mode-plus/issues/75)
